### ISSUE TITLE
Use Lucia instead of Auth.js

### ISSUE THREAD

**Issue by syhner** [syhner/elysia-kickstart#2]
- [ ] Ensure auth works on the edge

**Comment by patmood** [comment]
Does Auth.js have issues on the edge? I get this server error when using vercel edge functions

```
EvalError: Code generation from strings disallowed for this context
    at (node_modules/elysia/dist/compose.js:206:4)
    at (node_modules/elysia/dist/index.js:1:2274)
    at (node_modules/elysia/dist/index.js:6:4651)
    at (src/app/api/auth/index.js:5:5)
```

**Comment by syhner** [comment]
It does yes with the current setup. This issue will be resolved after Elyisa 1.0 release on March 16th.
