### ISSUE TITLE
Module not found on bun run db:push

### ISSUE THREAD

**Issue by Putnug1122** [syhner/elysia-kickstart#3]
The DB_URL and DB_AUTH_TOKEN is correct but fail to run `bun run db:push` on fresh install

```
$ drizzle-kit push:sqlite
No config path provided, using default path
Reading config file '/home/deta/Learning/Elysia/elysia-kickstart/drizzle.config.ts'
drizzle-kit: v0.19.13
drizzle-orm: v0.28.6

node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module '~/env'
Require stack:
- /home/deta/Learning/Elysia/elysia-kickstart/drizzle.config.ts
- /home/deta/Learning/Elysia/elysia-kickstart/node_modules/drizzle-kit/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/deta/Learning/Elysia/elysia-kickstart/drizzle.config.ts:2:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._compile (/home/deta/Learning/Elysia/elysia-kickstart/node_modules/drizzle-kit/index.cjs:8623:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .ts] (/home/deta/Learning/Elysia/elysia-kickstart/node_modules/drizzle-kit/index.cjs:8627:13)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/deta/Learning/Elysia/elysia-kickstart/drizzle.config.ts',
    '/home/deta/Learning/Elysia/elysia-kickstart/node_modules/drizzle-kit/index.cjs'
  ]
}

Node.js v18.17.1
error: script "db:push" exited with code 1 (SIGHUP)
```

**Comment by tenaz3** [comment]
Basically the env was not loaded properly.
Explanation: https://github.com/drizzle-team/drizzle-orm/issues/654#issuecomment-1586378907
Fix the import on `drizzle.config.ts`

`import { env } from './src/env';`
